config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  resources :invitations

  resources :votes

  resources :restaurants

  resources :password_resets

  root 'sessions#frontpage'

  resources :meetings 
  get 'meetings/:id/select_members' => 'meetings#select_members', as: :select_members
  post 'meetings/:id/submit_members' => 'meetings#submit_members'
  get 'meetings/:id/select_restaurants' => 'meetings#select_restaurants', as: :select_restaurants
  get 'meetings/:id/add_restaurants_by_address' => 'meetings#add_restaurants_by_address', as: :add_restaurants_by_address
  get 'meetings/:id/add_restaurants_by_location' => 'meetings#add_restaurants_by_location', as: :add_restaurants_by_location
  post 'meetings/:id/submit_restaurants' => 'meetings#submit_restaurants'
  get 'meetings/:id/update_vote' => 'meetings#update_vote', as: :update_vote
  get 'meetings/:id/set_decision' => 'meetings#set_decision', as: :set_decision
  get 'meetings/:id/get_default_restaurants' => 'meetings#get_default_restaurants', as: :get_default_restaurants
  get 'meetings/:id/search_restaurants' =>'meetings#search_restaurants', as: :search_restaurants
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  match '/signup', to: 'users#new', via: 'get'
  match '/signup/:invitation_token', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to:'sessions#destroy', via: 'delete'

end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
  has_many :meeting_memberships
  has_many :users, :through => :meeting_memberships, :autosave=>false
  has_many :meeting_restaurant_selections
  has_many :restaurants, :through => :meeting_restaurant_selections

  scope :future_meetings, lambda { where('DATE(date) >= ?', Date.today)}
  before_save :capitalize_title
  validates_presence_of :title, :message => "cannot be empty"
  validate :meeting_date_after_today

  def meeting_date_after_today
    if self.date < Time.now
      errors.add(:meeting, 'lunch date needs to be after current time')
    end
  end

  def capitalize_title
    self.title = self.title.split.map(&:capitalize).join(' ') unless self.title.blank?
  end

  def restaurants_attributes=(hash)
    hash.each do |sequence,restaurant_values|
      restaurants <<  Restaurant.find_or_create_by_name_and_url(restaurant_values[:name],\
        restaurant_values[:url])
    end
  end

  def self.usergoing(uid, mid)
    mm = MeetingMembership.where('user_id = ? AND meeting_id = ?', uid, mid)
    if mm.blank?
      return 'nothing'
    else
      return mm.first.going
    end
  end

  def self.userstatus(mid)
    userstatus = Hash.new
    meeting = Meeting.find_by_id(mid)
    meeting.users.sort_by{|x| x.username}.each do |user|
      going = usergoing(user.id, mid) || ''
      userstatus[user.username] = going
    end
    return Hash[userstatus.sort]
    #return userstatus
    # ust = userstatus.sort_by{|key, value| value}.reverse
  end

  def self.rsvpYuser(m, selection)
    ust = userstatus(m.id)
    ust.map{|key, _| key if ust[key]==("#{selection}")}.compact
  end

  def self.statuscounts(status)   
    status.each_with_object(Hash.new{|h, k| h[k] = '0'}) do |k, res|
      res[k[1]].succ!
    end
  end

  def self.check_and_send_reminder()
    Meeting.future_meetings.each do |m|
      if m.date - Time.now < 172800 and not m.reminder_sent
        ReminderMailer.send_reminder(m).deliver
        m.update_attributes(:reminder_sent=>true)
      end
    end
  end

  def self.pick_winner(m)
    restaurant_votes = Hash.new
    m.meeting_restaurant_selections.each{|y| restaurant_votes[y.restaurant_id] = y.vote_count}
    return 0 if restaurant_votes.empty? or restaurant_votes.max_by{|k,v| v}[1].to_i == 0
    hv_pair = restaurant_votes.select{|k, v| v == restaurant_votes.values.max}
    rid_highest_votes = hv_pair.reduce({}){|h,(k,v)| (h[v] ||= []) << k;h}.max[1]
    rid_yelp_review = Hash.new
    rid_highest_votes.each{|x| rid_yelp_review[x] = 
        [Restaurant.find_by_id(x).yelp_rating, Restaurant.find_by_id(x).review_count] }
    return rid_yelp_review.max_by{|k, v| v}[0]
  end

  def self.send_winner_restaurant()
    Meeting.future_meetings.each do |m|
      if m.date - Time.now <= 86410 and not m.result_sent
        ReminderMailer.send_result(m).deliver
        m.update_attributes(:result_sent=>true)
      end
    end
  end

  def self.aggregate_meeting_by_date(meetings)
    aggregated_meetings = {}
    meetings.each do |m|
      mdate = m.date.to_date
      if aggregated_meetings[mdate].blank?
        aggregated_meetings[mdate] = [m]
      else
        aggregated_meetings[mdate].push(m)
      end
    end
    aggregated_meetings
  end
end

app/controllers/meetings_controller.rb
include Yelp::V1::Review::Request
require 'yelp_query'
class MeetingsController < ApplicationController
  before_action :login_required
  before_action :set_meeting, only: [:show, :edit, :update, :destroy]

  layout 'menu'

  def index
    meetings = []
    Meeting.all.order('date').reverse.each{|x| meetings.push(x) if x.users.include?(current_user)}
    @meetings = Meeting.aggregate_meeting_by_date(meetings)
  end

  def show
    @meeting_id = params[:id] 
    @meeting = Meeting.find(@meeting_id)
    @user = current_user
    @uid = @user.nil? ? 0 : User.where('email = ?', @user.email).first.id
    @going = Meeting.usergoing(@uid, @meeting_id)
    mrs = MeetingRestaurantSelection.where('meeting_id = ?', params[:id])
    @meeting_mrs = @meeting.meeting_restaurant_selections.sort_by{|x| [x.vote_count, x['name']]}.reverse
    @inGroup = is_user_invited_and_confirmed?(@user, @meeting_id)
    @userlist = Meeting.userstatus(@meeting_id)
    @statuscounts = Meeting.statuscounts(@userlist)
    @result_sent = @meeting.result_sent
    @winner = Restaurant.find_by_id(Meeting.pick_winner(@meeting))
    @past = Time.now.to_date > @meeting.date
    if mrs.size == 0
      redirect_to :action => :select_restaurants
    end
  end

  def get_all_restaurants(meeting)
    meeting_mrs = Hash.new
    rests = meeting.restaurants
    rests.each do |r|
      mrs_id = MeetingRestaurantSelection.where('meeting_id = ? AND restaurant_id = ?', meeting.id, r.id).first.id
      votes = get_votes(mrs_id)
      if votes == 0
        upordown = nil
      elsif votes > 0
        upordown = 'up'
      else
        upordown = 'down'
      end
      meeting_mrs[r] = [get_votes(mrs_id), mrs_id, upordown]
    end
    return meeting_mrs
  end

  def new
    @meeting = Meeting.new
    @id = Meeting.all.empty? ? 1 : Meeting.maximum("id") + 1
    @new = true
    @allbuddies = User.allbuddies(current_user)
  end

  def edit
    @id = params[:id]
    @new = false
  end

  def create
    @meeting = Meeting.new(meeting_params)
    tid = ActiveRecord::Base.connection.execute "select last_value from meetings_id_seq"
    id = tid[0]['last_value'].to_i + 1
    users = get_users(params[:emailaddress], id)
    rn = params[:restaurant_name]
    input_restaurants = get_restaurant(params[:restaurantname])
    restaurants = rn.nil? ? input_restaurants :  input_restaurants + add_default_restaurants(rn)
    @meeting.users = users.push(current_user)
    @meeting.restaurants = restaurants
    respond_to do |format|
      if @meeting.save
        MeetingMembership.where('meeting_id = ? and user_id = ?', Meeting.maximum('id'), current_user.id).first.update_attributes(:going=>"Yes")
        @meeting.users.each do |u|  
          UserMailer.invite(u, meeting_url(@meeting)).deliver      
        end
        format.html { redirect_to @meeting, notice: 'Meeting was successfully created.' }
        format.json { render :show, status: :created, location: @meeting }
        
      else
        @allbuddies = User.allbuddies(current_user)
        format.html { render :new }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  def add_default_restaurants(restaurants)
    return [] if restaurants.nil?
    r = []
    restaurants.each do |rx|
      rr = eval(rx.gsub(":", "=>"))
      rt = Restaurant.where("lower(name)=?", rr['name'].downcase).first
      if rt.nil?
        cr = Restaurant.new
        cr['name'] = rr['name']
        cr['address'] = rr['address']
        cr['url'] = rr['url'].gsub("=>", ":")
        cr['photo_url'] = rr['photo_url'].gsub("=>", ":")
        cr['yelp_rating'] = rr['rating']
        cr['review_count'] = rr['review_count']
        cr['categories'] = rr['categories']
        cr.save
        r.push(cr)
      else
        r.push(rt) unless r.include?(rt)
      end
    end
    return r
  end


  def is_user_invited_and_confirmed?(user, mid)
    invited = Meeting.find(mid).users.include?(user) ? true : false
    status = Meeting.usergoing(user.id, mid)
    return false if status.nil?
    confirmed = status.include?('Y') ? true : false unless invited.blank?
    return invited & confirmed
  end

  def get_votes(mrs_id)
    votes = 0
    umvs = Vote.where('meeting_restaurant_selection_id = ?', mrs_id)
    return umvs.empty? ? 0 : umvs.map{|x| votes=votes+x.vote_counts}[0]
  end

  def update_vote
    uid = params[:uid]
    mrs_id = params[:mrs_id]
    vote = params[:vote] == 'up' ? 1 : -1
    id = params[:id]
    umv = Vote.where('user_id = ? AND meeting_restaurant_selection_id = ?', uid, mrs_id).first
    if umv.nil?
      umv = Vote.new(:user_id=>uid, :meeting_restaurant_selection_id=>mrs_id, :vote_counts=>vote)
    else
      umv.vote_counts = umv.vote_counts.to_i + vote
    end
    umv.save
    meeting_mrs = Meeting.find(id).meeting_restaurant_selections.sort_by{|x| x.vote_count}.reverse
    render :partial=>"restaurant_list", :locals=>{:meeting_mrs=>meeting_mrs, :uid=>uid} 
  end

  def set_decision
    uid = params[:uid]
    id = params[:id]
    decision = params[:decision]
    mmembership = MeetingMembership.where('user_id = ? AND meeting_id = ?', uid, id).first
    mmembership.going = decision
    mmembership.save
    inGroup = is_user_invited_and_confirmed?(User.find(uid), id)
    userlist = Meeting.userstatus(id)
    statuscounts = Meeting.statuscounts(userlist)
    meeting = Meeting.find(id)
    result_sent = meeting.result_sent
    winner = Restaurant.find_by_id(Meeting.pick_winner(meeting))
    past = Time.now.to_date > meeting.date
    render :partial=>"members_status", :locals=>{:statuscounts=>statuscounts, 
      :meeting=>meeting, :inGroup=>inGroup, :result_sent=>result_sent, 
      :winner=>winner, :past=>past}
  end

  def get_users(emails, id=0)
    return [] if emails.nil?
    users = []
    emails.each do |e|
      u = User.where({email: e})
      if u.empty?
        # send invitation
        invite = Invitation.new(:recipient_email=>e, :sender_id=>id)
        invite.save
        InvitationMailer.send_invitation(current_user, invite, signup_url,invite.token).deliver
      else
        users.push(u.first) unless users.include?(u.first)
      end
      #u = u.empty? ? User.new(:email=>e, :username=>e) : u.first
      #users.push(u) if not users.include?(u)
    end
    return users
  end

  def get_restaurant(rest, yelp=false)
    return [] if rest.nil?
    rests = []
    rest.each do |r|
      rname = yelp ? r['name'] : r
      rr = Restaurant.where("lower(name)=?", rname.downcase)
      rr = rr.empty? ? Restaurant.new(:name=>rname) : rr.first
      rests.push(rr) unless rests.include?(rr)
    end
    return rests
  end

  def get_default_restaurants
    client = Yelp::Client.new
    
    request = GeoPoint.new(
             :term => "restaurants",
             :latitude => params[:lati],
             :longitude => params[:longi]
              )
    response = client.search(request)
    
    render json: parse_restaurant_list(response).to_json
  end

  def search_restaurants
    client = Yelp::Client.new
    query = YelpQuery.new(params[:location], params[:name])
    puts query.to_yelp_params
    response = client.search(query)
    render json: parse_restaurant_list(response).to_json
  end

  def parse_restaurant_list(response)
    return [response['message']['text']] if response['businesses'].empty?
    @defaultrests = []
    response['businesses'].each do |business|
      info = Hash.new
      info['name'] = business['name'].gsub("'", "")
      info['distance'] = business['distance']
      info['is_closed'] = business['is_closed']
      info['rating'] = business['avg_rating']
      info['url'] = business['url']
      info['address'] = business['address1'] + business['address2'] + business['address3'] + ', ' + business['city'] + ', ' + ', ' + business['state'] + ' ' + business['zip']
      info['photo_url'] = business['photo_url']
      info['categories'] = parse_categories(business['categories'])
      info['review_count'] = business['review_count']
      @defaultrests.push(info)
    end
    #@defaultrests.push({'searchonyelp'=>soy})
    @defaultrests.sort_by!{|x| x['distance']}
    return @defaultrests
  end

  def parse_categories(categories)
    cuisines = []
    categories.each{|c| cuisines.push(c['name'])}
    return cuisines.join(' ')
  end
  
  def update
    users = get_users(params[:emailaddress], params[:id])
    restaurants = get_restaurant(params[:restaurantname])
    @meeting.users = users + @meeting.users
    @meeting.restaurants = restaurants + @meeting.restaurants
    @new = false
    
    respond_to do |format|
      if @meeting.update(meeting_params)
        @meeting.users.each do |u|  
          UserMailer.meeting_update(u, meeting_url(@meeting)).deliver      
        end
        format.html { redirect_to @meeting, notice: 'Meeting was successfully updated.' }
        format.json { render :show, status: :ok, location: @meeting }
      else
        format.html { render :edit }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @meeting.destroy
    respond_to do |format|
      format.html { redirect_to meetings_url }
      format.json { head :no_content }
    end
  end

  def select_members
    @meeting = Meeting.find(params[:id])
    @users = @meeting.users
    @allusers = []
    User.all.order('username').each{|x| @allusers.push(x) if not (x.meetings & current_user.meetings).empty?}
    @alluseremails = @users.pluck(:email) #get_user_emails(@allusers)
    # @alluseremails = []
    # @alluseremails = @allusers.map{|x| @alluseremails.push(x.email)}
  end

  def submit_members
    meeting = Meeting.find(params[:id])
    send_updates(meeting.users.pluck(:id), params[:user_id], meeting)
    meeting.users = meeting.users + get_users(params[:emailaddress], params[:id])
    redirect_to meeting
  end

  def send_updates(old_ids, new_ids, meeting)
    return if new_ids.nil?

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/views/meetings/_members_status.html.erb
<% if not @past %>
  <h3>Who's Going?</h3>
  <ul class="attendence-list">
    <li style="color: #5EA06F;"><h4><%= statuscounts['Yes'] %> going</h4>
<% else %>
  <h3>Who went?</h3>
  <ul class="attendence-list">
<% end %>
      <ul>
        <% Meeting.rsvpYuser(meeting, 'Yes').each do |k| %>    
            <li class="userlist">
            <img src="/assets/tick.gif" style="float:left"> <img alt="Account" class="menuavatarimage" src="<%=gravatar_url(User.find_by_username(k))%>)"> &nbsp;<span style="color: #5EA06F"><%=k %></span>
            </li>
        <% end %>
      </ul>
    </li>
<% if not @past %>
    <% not_going = Meeting.rsvpYuser(meeting, 'No') %>
    <% if not_going.size > 0 then %>
      <li style="color: #d9534f">
        <h4><%= statuscounts['No'] %> not going</h4>
        <ul>
        <% not_going.each do |k| %> 
            <li class="userlist">
            <img src="/assets/red-cross_small.png" style="float:left"> <img alt="Account" class="menuavatarimage" src="<%=gravatar_url(User.find_by_username(k))%>)"><span style="color:#d9534f">&nbsp;<%=k %></span>
            </li>
        <% end %>
        </ul>
      </li>
    <% end %>
    <% undecided = Meeting.rsvpYuser(meeting, 'Maybe') %>
    <% if undecided.size > 0 then %>
      <li style="color: #f0ad4e">
        <h4><%= statuscounts['Maybe'].to_i + statuscounts[''].to_i %> undecided</h4>
        <ul>
        <% undecided.each do |k| %> 
            <li class="userlist">
            <img src="/assets/question_mark.gif" style="float:left"> <img alt="Account" class="menuavatarimage" src="<%=gravatar_url(User.find_by_username(k))%>)"><span style="color: #f0ad4e">&nbsp; <%=k %></span>
            </li>
        <% end %>
          <% Meeting.rsvpYuser(meeting, nil).each do |k| %> 
              <li class="userlist">
              <img src="/assets/question_mark.gif" style="float:left"> <img alt="Account" class="menuavatarimage" src="<%=gravatar_url(User.find_by_username(k))%>)">&nbsp;<span style="color:#f0ad4e"> <%=k %></span>
              </li>
          <% end %>
        </ul>
      </li>
    <% end %>
  </ul>
<% end %>

<% if inGroup and not result_sent and not past%> 
  <%= link_to raw('Invite more <span class="glyphicon glyphicon-send"></span>'), :select_members, :class=>"btn btn-default" %>
  <br />
<% end %>
  
   
  <br>
  <% if inGroup and not past%>
    <div id="operation" style="font-size: 16px">
      <%= link_to raw('<span class="glyphicon glyphicon-pencil"></span>'), edit_meeting_path(meeting) %> |
      <%= link_to raw('<span class="glyphicon glyphicon-trash"></span>'), meeting, method:  :delete, data: { confirm: 'Are you sure?' } %> |
      <%= link_to raw('<span class="glyphicon glyphicon-arrow-left"></span>'), meetings_path %>
    </div>
  <% end %>
</div>

app/views/meetings/_restaurant_list.html.erb
<table class='restname vote' id='editr'>
  <% if meeting_mrs.size == 0 %>
    <p>No currently selected restaurants.</p>
  <% else %>
    <% meeting_mrs.each do |mrs| %>
      <%
      vote_count = mrs.vote_count
      my_vote = mrs.votes.find {|v| v.user_id.to_i == uid.to_i }
      up_arrow_class = 'arrow-up'
      down_arrow_class = 'arrow-down'
      already_voted_up = my_vote && my_vote.vote_counts > 0
      already_voted_down = my_vote && my_vote.vote_counts < 0

      if already_voted_up then
        up_arrow_class = 'arrow-uped'
      end
      if already_voted_down then
        down_arrow_class = 'arrow-downed'
      end
      %>

      <tr>
        <td style="text-align: center; vertical-align: top; min-width: 4em">
          <% if already_voted_up %>
            <span class="glyphicon glyphicon-thumbs-up votedcolor" id="tupa"
              onclick="alert('You have already up voted!')">
          <% else %>
            <span class="glyphicon glyphicon-thumbs-up" id="tupa"
              onclick="changeVote('up', <%= mrs.id %>)">
          <% end %>
          </span>  
          <span class="votenumber"><%= vote_count %></span>   
          <% if already_voted_down %>
            <span class="glyphicon glyphicon-thumbs-down votedcolor" id="tdowna"
              onclick="alert('You have already down voted!')">
          <% else %>
            <span class="glyphicon glyphicon-thumbs-down" id="tdowna"
              onclick="changeVote('down', <%= mrs.id %>)">
            </span>
          <% end %>
        </td>
        <td>
        
            <% if not mrs.restaurant.nil? %>
            <a href="<%=restaurant_path(mrs.restaurant)%>">
              <% if mrs.restaurant['photo_url'].nil? %>
                <img class="thumb" height="90" width="90" alt=<%=mrs.restaurant.name%> src=<%=image_path("default.jpg")%>>
              <% else %>
                <img class="thumb" height="90" width="90" alt=<%=mrs.restaurant.name%> src=<%=mrs.restaurant['photo_url']%>>
              <% end %>
            </a>
            <% end %>
            
            <div class="restinfo" style="display: inline-block;">
                <% if mrs.restaurant.url.nil? %>
                  <%= link_to mrs.restaurant.name, restaurant_path(mrs.restaurant), :class=>'   yelplink ', :data=>{:placement=> "bottom", :content=>"Not from Yelp", :trigger=>"hover"} %>
                <% else %>
                  <%= link_to mrs.restaurant.name, mrs.restaurant.url, :class=>'yelplink', :data=>{ :placement=> "bottom", :content=>"Rating on Yelp is #{mrs.restaurant.  yelp_rating}" , :trigger=>"hover"} %>
                <% end %>
                
                <p style="padding-left: 15px; font-size:16px" class=""> 
                  <% r = mrs.restaurant['yelp_rating'].to_i %>
                  <% for i in (1..r) %>
                    <img src=<%=image_path("star.png")%>>
                  <% end %>
                  <% if r != 0 && mrs.restaurant['yelp_rating'].include?('.') %>
                    <img src=<%=image_path("half_star.png")%>>
                    <% for i in (r+1..4) %>
                      <img src=<%=image_path("grey_star.png")%>>
                    <% end %>
                  <% else %>
                    <% for i in (r..4) %>
                      <img src=<%=image_path("grey_star.png")%>>
                    <% end %>
                  <% end %>
                     <%#=mrs.restaurant['yelp_rating'] %>
                  
                  <%# if mrs.restaurant['review_count'] > 0 %>
                  <span style="font-size:12px; font-style:italic"> <%= mrs.restaurant['review_count']  %> reviews on Yelp</span>
                  <%# end %> 
                </p>
      
                <p class="restaurant_categories "><%=mrs.restaurant['categories'] %></p>


            </div>

            <div class="address">
              <% if not mrs.restaurant['address'].blank? %>
                <span class="glyphicon glyphicon-map-marker"></span>
                <address>
                  <% splitarray = mrs.restaurant['address'].split(',')%>
                  <%=splitarray[0] %>
                  <br >
                  <% gaddress = splitarray[1..-1] %>
                  <% if not gaddress.blank? %>
                    <%=gaddress.include?(' ') ? gaddress.reject!{|c| c == " "}.join(',') : gaddress.      join(',')%> 
                  <% end %>
                  
                </address>
              <% end %>
            </div>
      </td>
    </tr>
    <% end %>

	</table>
  <% end %>
  <script>
  $(document).ready(function(){
    $(".yelplink").popover();
    //Convert address tags to google map links
   $('address').each(function () {
      var link = "<a style='color: #555' href='http://maps.google.com/maps?q=" + encodeURIComponent( $(this).text() ) + "' target='_blank'>" + $(this).html() + "</a>";
      $(this).html(link);
   });
  })

  </script>

app/views/meetings/edit.html.erb
<div class="listing">

<h1>Make a change to a lunch setting</h1>

<%= render 'form' %>

<%= link_to raw('<span class="glyphicon glyphicon-arrow-left"></span>'), @meeting %>
<%#= link_to 'Back', meetings_path %>

app/views/meetings/index.html.erb
<% provide(:title, "Meeting index") %>


<h1><%=current_user.username%> Lunch Calendar</h1>
<% if @meetings.blank? %>
  <h3>No lunch scheduled for <%=current_user.username %>. Create one now! </h3>
<% end %>
<%= link_to raw('<span class="glyphicon glyphicon-plus"></span> Create New Lunch'),    new_meeting_path, :class=>'btn btn-primary btn-md' %>

<div class="listingbox">
  <ul class="listmeetings">
  <% @meetings.each_pair do |date, meetings| %>

    <li class="date-indicator">
      <%= link_to date.in_time_zone.strftime("%a, %b %d, %Y"), meetings[0], :class=>"meetingtime" %>
    </li>
    <li >
      <ul style="padding: 0">
        <div class="detail-container">
          <% meetings.each do |meeting| %>
            <li class="meetingsamedate">              
              <div class="unit sizetime">
                <%= meeting.date.in_time_zone.strftime("%l:%M %p") %>
              </div>
              <div class="unit sizemain">
                <div class="title">
                  <%= link_to meeting.title.split.map(&:capitalize).join(' '),meeting %> 
                </div>
                <div class="description">
                  <%=meeting.description %>
                </div>
                <div class='peoplecount' >
                     <%#= pluralize_to_sentence(meeting.users.count) %>
                  <%= pluralize(Meeting.rsvpYuser(meeting, 'Yes').count, 'person') %> <%= 'is'.pluralize(Meeting.rsvpYuser(meeting, 'Yes').count) %> going <%#= pluralize  meeting .users.count,    'is', 'are')%> <%#='person'.  pluralize(meeting .users.count) %>  
                     <%#='person is going'.pluralize(meeting.users.count)%> 
                     <%#=pluralize(meeting.users.count, 'person')%> <%#="is going".       pluralize(meeting.users.count) %><%#=pluralize( meeting.  users.   count, 'is', 'are') %> 
                </div>
              </div> 

            </li>
          <% end %>
        </div>
      </ul>
    </li>
      
  <% end %>
  </ul>
</div>

app/views/meetings/new.html.erb
<%#= javascript_include_tag "application" %>

<div class="listing">
  
<h1>Create a new meeting</h1>

<%= render 'form' %>

</div>

app/views/meetings/select_restaurants.html.erb
<% is_new = @restaurants.size == 0 %>

<%=form_tag 'submit_restaurants' do %>
  <h1>Venue Candidates</h1>
  <p>Select venue candidates for
  
    <b><%= @meeting.title %></b> - 
    <%= @meeting.description %> on
    <b>
      <%= @meeting.date.in_time_zone.strftime("%a, %b %d, %Y") %>
      <%= @meeting.date.in_time_zone.strftime("%l:%M %p") %>
    </b>.
  </p>

  <% if @restaurants.size > 0 %>
    <ul>
      <% @restaurants.each do |rest| %>
        <li><%= rest.name %></li>
      <% end %>
    </ul>
  <% else %>
    <p><em>Add some restaurants to the list kickstart it.</em></p>
  <% end %>

  <a href="add_restaurants_by_address" class="btn <%= is_new ? 'btn-primary' : 'btn-default' %>">Add restaurants</a>
  <% if not is_new %>
    <a href="./" class="btn btn-primary">Back to Event</a>
  <% end %>
<% end %>