config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  resources :invitations

  resources :votes

  resources :restaurants

  resources :password_resets

  root 'sessions#frontpage'

  resources :meetings 
  get 'meetings/:id/select_members' => 'meetings#select_members', as: :select_members
  post 'meetings/:id/submit_members' => 'meetings#submit_members'
  get 'meetings/:id/select_restaurants' => 'meetings#select_restaurants', as: :select_restaurants
  get 'meetings/:id/add_restaurants_by_address' => 'meetings#add_restaurants_by_address', as: :add_restaurants_by_address
  get 'meetings/:id/add_restaurants_by_location' => 'meetings#add_restaurants_by_location', as: :add_restaurants_by_location
  post 'meetings/:id/submit_restaurants' => 'meetings#submit_restaurants'
  get 'meetings/:id/update_vote' => 'meetings#update_vote', as: :update_vote
  get 'meetings/:id/set_decision' => 'meetings#set_decision', as: :set_decision
  get 'meetings/:id/get_default_restaurants' => 'meetings#get_default_restaurants', as: :get_default_restaurants
  get 'meetings/:id/search_restaurants' =>'meetings#search_restaurants', as: :search_restaurants
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  match '/signup', to: 'users#new', via: 'get'
  match '/signup/:invitation_token', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to:'sessions#destroy', via: 'delete'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :meeting_memberships
  has_many :meetings, through: :meeting_memberships
  belongs_to :invitation

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates:email, presence: true, 
  					format: {with: VALID_EMAIL_REGEX },
  					uniqueness: { case_sensitive: false }
  before_save { self.email = email.downcase }
  #before_create :create_remember_token
  before_create {generate_token(:remember_token)}
  
  has_secure_password
  #validates :password, length: { minimum: 6 }

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end

  def User.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  def invitation_token
    invitation.token if invitation
  end

  def invitation_token=(token)
    self.invitation = Invitation.find_by_token(token)
  end

  def self.allbuddies(user)
    buddies = []
    User.all.order('username').each{|x| buddies.push(x) if not (x.meetings & user.meetings).empty?}
    if not buddies.empty?
      buddies = buddies - [user]
    end
    return buddies
  end

  private

    def create_remember_token
      self.remember_token = User.digest(User.new_remember_token)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :login_required, except: [:new, :create]
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  layout :resolve_layout

  def index
    @users = []
    User.all.order('username').each{|x| @users.push(x) if not (x.meetings & current_user.meetings).empty?}
    @users = @users - [current_user] if not @users.empty?
  end

  def show
    @meeting = []
    @user.meetings.each do |m|
      @meeting.push(m) if current_user.meetings.include?(m)
    end
    @meeting = @meeting.sort_by{|x| x['date']}
    @future_meetings = @meeting.reject{|x| x.date < Date.today}
    @old_meetings = Meeting.aggregate_meeting_by_date((@meeting - @future_meetings).sort_by!{|x| x['date']}.reverse)
    @next_meeting = @future_meetings.first
  end

  def new
    itken = params[:invitation_token] || @invitation_token
    if not itken.nil?
      @user = User.new(:invitation_token => itken)
      @user.email = @user.invitation.recipient_email if @user.invitation
    else
      @user = User.new
    end
  end
 
  def edit
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        sign_in @user
        if not params[:user][:invitation_token].blank?
          sid = @user.invitation.sender_id
          if sid.to_i > 0
            meeting = Meeting.find_by_id(sid)
            meeting.users.push(@user)
            meeting.save
            format.html { redirect_to meeting, notice: 'User was successfully created.'}
          else
            format.html { redirect_to @user, notice: 'User was successfully created.' }
            format.json { render :show, status: :created, location: @user }
          end
        else
          format.html { redirect_to @user, notice: 'User was successfully created.' }
          format.json { render :show, status: :created, location: @user }
        end
      else
        @invitation_token =  params[:user][:invitation_token]
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

 
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation, :invitation_token)
    end

    def resolve_layout
      case action_name
      when 'new'
        'sessions'
      else
        'menu'
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
<%= render 'shared/error', :target=>@user %>
  <%# if @user.errors.any? %>
  <!--   <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div> -->
  <%# end %>
<div class="panel panel-default">
  <div class="panel-heading">     
    <h3 class="panel-title">Basic info</h3>
  </div>
    
  <div class="panel-body">
    <div class="form-group">
      <%= f.label :username %>
      <%= f.text_field :username %>
    </div>
    <div class="form-group">
      <%= f.label :email %>
      <%= f.text_field :email %>
    </div>
    <div class="form-group">
      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
    </div>
    <%= f.hidden_field :invitation_token %>
    </div>
  
  </div >

  <% if not @user.email.nil? %>
  <div class="panel panel-default">
    <div class="panel-heading">     
      <h3 class="panel-title">Image</h3>
    </div>
    <div class="panel-body">
      <div class="newmemberfields">
        <%= gravatar_for @user %>
        <a href="http://gravatar.com/emails">change</a>
      </div>
    </div>
  </div>
  <% end %>
  <br >
  <%= f.submit class: "btn btn-large btn-primary" %>
<% end %>

app/views/users/edit.html.erb
<div class="listing">

<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Cancel', users_path %> 

app/views/users/index.html.erb
<% provide(:title, "User index") %>

<div class="listing table-responsive" style="cursor: default">
 
            <h1>Lunch buddies for <%=current_user.username%></h1>
            <p>people that you went to eat with or will be eating with</p>
        
      <%#= link_to raw('<span class="glyphicon glyphicon-plus"></span> Create New Lunch'),    new_meeting_path, :class=>'btn btn-primary btn-lg' %>
    
  <% if @users.empty? %>
    <div class="emptyuser">
      <h3 class="listingh">No lunch buddy for <%=current_user.username%> yet....</h3>
      <p>Haven't had lunch meet with anybody yet? Start to invite your friends over now!</p>
      
    </div>
  <% else %>    
  
    <div class="listingbox">
      <ul class="listmeetings">
        <div class="figureset">
          <% @users.each do |user| %>
            <li style="overflow:hidden">
                <div style="margin: 10px">
                  <a href=<%=user_path(user)%> class="avatarimage" style="display:block; background-image: url(<%= gravatar_url(user)%>)"></a>
                </div>
                <div class="figureset-description">
                  <h5><%= link_to user.username, user_path(user) %></h5>
                  <h6><%= user.email %></h6>
                  <div></div>
                </div>       
            </li>
          <% end %>
        </div>
       <br >
      </ul>
    </div>
  <% end %>

<!-- <table class="tlisting table table-striped table-bordered">
  <thead>
    <tr class="thead">
      <th></th>
      <th>Username</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%# @users.each do |user| %>
      <tr>
        <td><%#= gravatar_for user %></td>
        <td><%#= user.username %></td>
        <td><%#= user.email %></td>
        <td><%#= link_to 'Show', user %></td>
        <%# if user.email == current_user.email %>
          <td><%#= link_to 'Edit', edit_user_path(user) %></td>
          <td><%#= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%# else %>
          <td></td>
          <td></td>
        <%# end %>
      </tr>
    <%# end %>
  </tbody>
</table> -->

<%#= link_to 'New User', new_user_path %>

</div>

app/views/users/new.html.erb
<h1>New user</h1>

<div class="span6 offset3">
<%= render 'form' %>
<%#= link_to '<i class="icon icon-arrow-left"></i>'.html_safe, users_path %>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.username) %>

<% flash.each do |key, value| %>
  <div class="flash <%=flash_class(key) %>">
        <%= value %>
  </div>
<% end %>

<div class="listingbox">
  <% if current_user == @user %>
    <h1>Hello, <%= @user.username %>!</h1>
  <% else %>
    <h2><%= @user.username %>'s Lunch Meetings </h2>
  <% end %>
  <% if not @next_meeting.blank? %>
  <div class="nextlunch">
    <% if current_user == @user %>
      <h3 style="color: #fff; padding-top: 10px">Your next lunch: </h3>
    <% else %>
      Next lunch: <br>
    <% end %>
    <div class="datecalendar">
      <time class="sheet">
        <span class="month"><%=@next_meeting.date.strftime("%b")%></span>
        <span class="day"><%=@next_meeting.date.day%></span>
      </time>
    </div>
    <div class="lunch-date">
      <div class="date-display" style="font-size: 150%">
        <%= link_to @next_meeting.title, @next_meeting %>
      </div>
      <p><%=@next_meeting.description %></p>
      <div class="timetext" style="color: #000; font-weight: 300; font-size:16px">
        <%= @next_meeting.date.in_time_zone.strftime("%l:%M %p") %>
      </div>
    </div>
    <% else %>
      <p> No future lunch scheduled. </p>
      <a href="/meetings/new" class="btn btn-primary">Schedule a lunch!</a>
    <% end %>
  </div>

  
  
  
  <% if @old_meetings.size > 0 then %>
    <h3>Previous lunch meetings:</h3>
    <ul class="listmeetings">
    <% @old_meetings.each_pair do |date, meetings| %>
      
      <li class="date-indicator">
        <%= link_to date.in_time_zone.strftime("%a, %b %d, %Y"), meetings[0], :class=>"meetingtime" %>
      </li>
      <li >
        <ul style="padding: 0">
          <div class="detail-container" style="min-height: 40px">
            <% meetings.each do |meeting| %>
              <li class="meetingsamedate">              
                <div class="unit sizetime" style="padding-top: 15px">
                  <%= meeting.date.in_time_zone.strftime("%l:%M %p") %>
                </div>
                <div class="unit sizemain">
                  <div class="title">
                    <%= link_to meeting.title.split.map(&:capitalize).join(' '),meeting %> 
                  </div>
                  <div class="description">
                    <%=meeting.description %>
                  </div>
                  
                </div> 

              </li>
            <% end %>
          </div>
        </ul>
      </li>
    
    <% end %>
    </ul>
  <% end %>
  
</div>