config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  resources :invitations

  resources :votes

  resources :restaurants

  resources :password_resets

  root 'sessions#frontpage'

  resources :meetings 
  get 'meetings/:id/select_members' => 'meetings#select_members', as: :select_members
  post 'meetings/:id/submit_members' => 'meetings#submit_members'
  get 'meetings/:id/select_restaurants' => 'meetings#select_restaurants', as: :select_restaurants
  get 'meetings/:id/add_restaurants_by_address' => 'meetings#add_restaurants_by_address', as: :add_restaurants_by_address
  get 'meetings/:id/add_restaurants_by_location' => 'meetings#add_restaurants_by_location', as: :add_restaurants_by_location
  post 'meetings/:id/submit_restaurants' => 'meetings#submit_restaurants'
  get 'meetings/:id/update_vote' => 'meetings#update_vote', as: :update_vote
  get 'meetings/:id/set_decision' => 'meetings#set_decision', as: :set_decision
  get 'meetings/:id/get_default_restaurants' => 'meetings#get_default_restaurants', as: :get_default_restaurants
  get 'meetings/:id/search_restaurants' =>'meetings#search_restaurants', as: :search_restaurants
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  match '/signup', to: 'users#new', via: 'get'
  match '/signup/:invitation_token', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to:'sessions#destroy', via: 'delete'

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :meeting_restaurant_selections
  has_many :meetings, :through => :meeting_restaurant_selections

  before_save :capitalize_name, :url_add_http
  validates_uniqueness_of :name, scope: [:url]

  def capitalize_name
  	#self.name.capitalize!
    self.name = self.name.split.map(&:capitalize).join(' ')
  end

  def url_add_http
  	if not self.url.blank?
  		if not self.url.include?("http")
  			self.url = "http://" + self.url
  		end
  	end
  end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]
  layout "sessions"

  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.all.order('lower(name)')
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :address, :url, :photo_url, :categories, :review_count, :yelp_rating)
    end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_form.html.erb
<%= form_for(@restaurant) do |f| %>
  <% if @restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
      <% @restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Basic info</h3>
    </div>
    <div class="panel-body">
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name %>
      </div>
      <div class="form-group">
        <%= f.label :address %>
        <%= f.text_field :address %>
      </div>
      <div class="form-group">
        <%= f.label :url %>
        <%= f.text_field :url %>
      </div>
      <div class="form-group">
        <%= f.label :photo_url %>
        <%= f.text_field :photo_url %>
      </div>
      <div class="form-group">
        <%= f.label :categories %>
        <%= f.text_field :categories %>
      </div>
      <div class="form-group">
        <%= f.label :review_count %>
        <%= f.text_field :review_count %>
      </div>
      <div class="form-group">
        <%= f.label :yelp_rating %>
        <%= f.text_field :yelp_rating %>
      </div>
    </div>
  </div>
<%= f.submit :class=>"btn btn-primary"%>
<% end %>

app/views/restaurants/edit.html.erb
<div class="listing">
<h1>Editing restaurant</h1>

<%= render 'form' %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<div class="listing table-responsive" style="margin-bottom: 10px">
  <div class="topbar">
    <div class="buddiestopbar">
      <div class="leftentity">
        <div class="contentwrapper">
          <h1>Restaurants</h1>
          <h3>restaurants that have been added by our users</h3>
        </div>
      </div>
    </div>
    <div class="newmeeting">
      <div class="nmeetingwrapper">
        
        <%=link_to raw('<span class="glyphicon glyphicon-plus"></span> Add New Restaurant'), new_restaurant_path, :class=>"btn btn-default btn-lg" %>
      </div>
    </div>
  </div>
</div>

<div class="listingbox">
  <ul class="listmeetings">
  <% @restaurants.each do |restaurant| %>
    <li class="meeting-divider">
          <div class="figureset">
            <div class="mainname">
              <a href=<%=restaurant_path(restaurant)%> class="avatarimage" style="padding-left:0; display:block;">
                <% if restaurant['photo_url'].nil? %>
                  <img alt=<%=restaurant['name']%> height="85" width="80" src=<%=image_path("default.jpg")%>>
                <% else %>
                <img alt=<%=restaurant['name']%> height="80" width="90" src=<%=restaurant[  'photo_url']%>>
                <% end %>
              </a>
              <div class="figureset-description">
                <h5><%= link_to restaurant.name, restaurant_path(restaurant) %></h5>
                <h6>
                  <% if restaurant.url.nil? %>
                    <%=link_to "Add a url for this restaurant", edit_restaurant_path( restaurant) %>
                  <% else %>
                    <%= link_to restaurant.url, restaurant.url %></h6>
                  <% end %>
                <div></div>
              </div>
            </div>

            <div class="addresses">
              <% if not restaurant['address'].blank? %>
              <span class="glyphicon glyphicon-map-marker"></span>
              <i class="icon icon-map-marker"></i>
              <address>
                <% splitarray = restaurant['address'].split(',')%>
                <%=splitarray[0] %>
                <br >
                <% gaddress = splitarray[1..-1] %>
                <% if not gaddress.blank? %>
                  <%=gaddress.include?(' ') ? gaddress.reject!{|c| c == " "}.join(',') : gaddress.join(',')%> 
                <% end %>
                
              </address>
              <% end %>
            </div>
          </div>
        </li>
        <hr>

  <% end %>
  </ul>


<script>
$(document).ready(function () {
   //Convert address tags to google map links
   $('address').each(function () {
      var link = "<a style='color: #555' href='http://maps.google.com/maps?q=" + encodeURIComponent( $(this).text() ) + "' target='_blank'>" + $(this).html() + "</a>";
      $(this).html(link);
   });
});
</script>

app/views/restaurants/new.html.erb
<div class="listing">
<h1>New restaurant</h1>

<%= render 'form' %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<% flash.each do |key, value| %>
  <div class="<%=flash_class(key) %>">
        <%= value %>
  </div>
<% end %>

<div class="rbox">
  <h1 class="rheadername"><%=link_to @restaurant['name'], @restaurant['url'] %></h1>
  <br >
  <% if not @restaurant['yelp_rating'].nil? %>
  <h3>Yelp rating: <%=@restaurant['yelp_rating'] %></h3>
  <% end %>

  <% if not @restaurant['address'].blank? %>   
    <div class="map-container">
      <div class="mapbox-map">
      </div>
      <div class="mapbox-text">
        <h5>Address: </h5>
        <address>
            <% splitarray = @restaurant['address'].split(',')%>
            <%=splitarray[0] %>  
            <br >
            <% gaddress = splitarray[1..-1] %>
            <% if not gaddress.blank? %>
              <%=gaddress.include?(' ') ? gaddress.reject!{|c| c == " "}.join(',')  : gaddress.join(',')%> 
            <% end %>
          
        </address>
      </div>
    </div>
  <% else %>
    <div><h5>Please add an url or address </h5></div>
  <% end %>
</div>


<!-- <ul class="listmeetings">
  
    <li class="meeting-divider">
          <div class="figureset">
            <a href=<%=restaurant_path(@restaurant)%> class="avatarimage" style="display:block;">
              <% if @restaurant['photo_url'].nil? %>
                <i class="icon icon-cutlery"></i>
              <% else %>
              <img alt=<%=@restaurant['name']%> height="80" width="90" src=<%=@restaurant['photo_url']%>>
              <% end %>
            </a>
            <div class="figureset-description">
              <h5>Name: <%=@restaurant.name%></h5>
              <h5>Address: <%=@restaurant.address%></h5>
              <h6>
                <% if @restaurant.url.nil? %>
                  <%=link_to "Add a url for this restaurant", edit_restaurant_path(@restaurant) %>
                <% else %>
                  <%= link_to @restaurant.url, @restaurant.url %></h6>
                <% end %>
              <div></div>
            </div>
          </div>
        </li>

  
  </ul> -->
<br >
<%= link_to raw('<span class="glyphicon glyphicon-pencil"></span>'), edit_restaurant_path(@restaurant) %> |
<%= link_to raw('<span class="glyphicon glyphicon-trash"></span>'), @restaurant, method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to raw('<span class="glyphicon glyphicon-arrow-left"></span>'), restaurants_path %>