config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  resources :invitations

  resources :votes

  resources :restaurants

  resources :password_resets

  root 'sessions#frontpage'

  resources :meetings 
  get 'meetings/:id/select_members' => 'meetings#select_members', as: :select_members
  post 'meetings/:id/submit_members' => 'meetings#submit_members'
  get 'meetings/:id/select_restaurants' => 'meetings#select_restaurants', as: :select_restaurants
  get 'meetings/:id/add_restaurants_by_address' => 'meetings#add_restaurants_by_address', as: :add_restaurants_by_address
  get 'meetings/:id/add_restaurants_by_location' => 'meetings#add_restaurants_by_location', as: :add_restaurants_by_location
  post 'meetings/:id/submit_restaurants' => 'meetings#submit_restaurants'
  get 'meetings/:id/update_vote' => 'meetings#update_vote', as: :update_vote
  get 'meetings/:id/set_decision' => 'meetings#set_decision', as: :set_decision
  get 'meetings/:id/get_default_restaurants' => 'meetings#get_default_restaurants', as: :get_default_restaurants
  get 'meetings/:id/search_restaurants' =>'meetings#search_restaurants', as: :search_restaurants
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  match '/signup', to: 'users#new', via: 'get'
  match '/signup/:invitation_token', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to:'sessions#destroy', via: 'delete'

end

app/views/layouts/_header.html.erb
<link href='http://fonts.googleapis.com/css?family=PT+Sans:400,700' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Leckerli+One' rel='stylesheet' type='text/css'>

<div class="site-header">
  
  <ul class="nav nav-pills" style="float: right">
    <li><%=link_to "Lunches", meetings_url, :class=>'stylea'%></li>
    <li><%=link_to "Buddies", users_url, :class=>'stylea'%></li>
    <li class="dropdown" id="fat-menu">

      <a style="color: black" class="dropdown-toggle" data-toggle="dropdown" href="/"><img alt="Account" class="menuavatarimage" src="<%=gravatar_url(current_user)%>)"><span class="caret" style="margin-top: -2px; margin-left: 5px;"></span></a>
      
         <ul class="dropdown-menu" role="menu">
           <li role="profile">
            <%= link_to "Profile", current_user %>
           </li>
           <li role="Settings">
            <%= link_to "Settings", edit_user_path( current_user) %>
           </li>
           <li class="divider"></li>
           <li role="Sign out">
            <%= link_to "Sign out", signout_path, method: "delete" %>
           </li>
         </ul>
      

    </li>
  </ul>
  <h1 class="site-title">
    <a href="/">Lunch Voting</a>
  </h1>
</div>

app/views/layouts/empty.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lunchvoting | <%=yield(:title)%></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
</head>
<body class="frontpage">
  
  <%= yield %>

</body>
</html>

app/views/layouts/menu.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lunchvoting | <%=yield(:title)%></title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Abril+Fatface' rel='stylesheet' type='text/css'>
</head>
<body>
  <div id="frame">
    <%= render "layouts/header" %>
  	<div class="pagecontent">
  		<%= yield %>
  	</div>
  </div>
</body>
</html>

app/views/layouts/sessions.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lunchvoting | <%=yield(:title)%></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Abril+Fatface' rel='stylesheet' type='text/css'>
</head>
<body>
  <div id="frame">
  <h1 class="site-title">
    <a href="/">Lunch Voting</a>
  </h1>

	<div>
    <div class="pagecontent">
		  <%= yield %>
    </div>
	</div>
</div>

</body>
</html>